# Generated by Django 4.0.6 on 2022-07-22 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PoemApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poem',
            name='form',
        ),
        migrations.DeleteModel(
            name='Form',
        ),
    ]
