# Generated by Django 4.0.6 on 2022-08-11 07:09

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('PoemApp', '0002_remove_poem_form_delete_form'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poem',
            name='imageUrl',
        ),
        migrations.AddField(
            model_name='poem',
            name='about_poem',
            field=models.CharField(default=datetime.datetime(2022, 8, 11, 7, 9, 10, 50313, tzinfo=utc), max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='poem',
            name='form',
            field=models.CharField(choices=[('GHAZAL', 'Ghazal'), ('HAIKU', 'haiku'), ('ITALIAN SONNET', 'Italian Sonnet'), ('LIMERICK', 'Limerick'), ('SESTINA', 'sestina'), ('TANKA', 'Tanka'), ('ELIZABETHAN SONNET', 'Elizabethan Sonnet'), ('CONTEMPORARY SONNET', 'Contemporary Sonnet'), ('VILLANELLE', 'Villanelle'), ('FREE VERSE', 'Free Verse')], default='GHAZAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='poem',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='poem',
            name='genre',
            field=models.CharField(choices=[('FAMILY', 'family'), ('LOVE', 'love'), ('SADNESS', 'sadness'), ('FRIENDSHIP', 'friendship'), ('RELATIONSHIP', 'relationship'), ('JOY', 'joy')], default='FAMILY', max_length=20),
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
    ]
